export type RiskLevel='LOW'|'MEDIUM'|'HIGH';
export type Supplier={id:string;name:string;location:string;industry:string;products:string[];deliveryScore:number;qualityScore:number;financialScore:number;priceScore:number;complianceScore:number;capacityScore:number;locationScore:number;dependencyScore:number;sustainabilityScore:number;totalDeliveries:number;onTimeDeliveries:number;delayedDeliveries:number;failedDeliveries:number;averageDeliveryTime:number;capacity:number;currentOrders:number;availableCapacity:number;previousRiskScore:number;certifications:string[];partnershipYears:number;price:number};
export const baseSuppliers:Supplier[]=[
{id:'abc',name:'ABC Electronics',location:'Coimbatore',industry:'Electronics',products:['Control boards','Sensors'],deliveryScore:72,qualityScore:86,financialScore:68,priceScore:74,complianceScore:91,capacityScore:52,locationScore:70,dependencyScore:78,sustainabilityScore:81,totalDeliveries:1280,onTimeDeliveries:1012,delayedDeliveries:238,failedDeliveries:30,averageDeliveryTime:8,capacity:100,currentOrders:91,availableCapacity:9,previousRiskScore:64,certifications:['ISO 9001','RoHS'],partnershipYears:6,price:9690},
{id:'nova',name:'Nova Components',location:'Chennai',industry:'Industrial Components',products:['Motors','Connectors'],deliveryScore:94,qualityScore:91,financialScore:88,priceScore:82,complianceScore:95,capacityScore:82,locationScore:84,dependencyScore:42,sustainabilityScore:89,totalDeliveries:1540,onTimeDeliveries:1448,delayedDeliveries:78,failedDeliveries:14,averageDeliveryTime:5,capacity:100,currentOrders:82,availableCapacity:18,previousRiskScore:27,certifications:['ISO 14001','IATF 16949'],partnershipYears:8,price:9140},
{id:'prime',name:'Prime Logistics',location:'Bengaluru',industry:'Logistics',products:['Freight','Warehousing'],deliveryScore:87,qualityScore:84,financialScore:76,priceScore:79,complianceScore:88,capacityScore:68,locationScore:90,dependencyScore:55,sustainabilityScore:76,totalDeliveries:2100,onTimeDeliveries:1827,delayedDeliveries:235,failedDeliveries:38,averageDeliveryTime:4,capacity:100,currentOrders:68,availableCapacity:32,previousRiskScore:43,certifications:['ISO 45001'],partnershipYears:4,price:7850},
{id:'tech',name:'TechSource Industries',location:'Pune',industry:'Industrial Automation',products:['PLCs','Drives'],deliveryScore:83,qualityScore:88,financialScore:72,priceScore:67,complianceScore:90,capacityScore:76,locationScore:78,dependencyScore:61,sustainabilityScore:84,totalDeliveries:980,onTimeDeliveries:823,delayedDeliveries:139,failedDeliveries:18,averageDeliveryTime:7,capacity:100,currentOrders:76,availableCapacity:24,previousRiskScore:39,certifications:['ISO 9001','REACH'],partnershipYears:5,price:10800},
{id:'global',name:'Global Parts Ltd.',location:'Mumbai',industry:'Raw Materials',products:['Fasteners','Castings'],deliveryScore:61,qualityScore:73,financialScore:59,priceScore:62,complianceScore:72,capacityScore:60,locationScore:58,dependencyScore:86,sustainabilityScore:64,totalDeliveries:760,onTimeDeliveries:555,delayedDeliveries:181,failedDeliveries:24,averageDeliveryTime:11,capacity:100,currentOrders:88,availableCapacity:12,previousRiskScore:69,certifications:['ISO 9001'],partnershipYears:3,price:6420}
];
export const riskWeights={delivery:.18,quality:.12,financial:.14,price:.08,compliance:.1,capacity:.12,location:.08,dependency:.1,sustainability:.08};
export function calculateRiskScore(s:Supplier, controls={delay:0,quality:0,capacity:0,price:0,dependency:0,location:0}){const factors={delivery:100-s.deliveryScore+controls.delay,quality:100-s.qualityScore+controls.quality,financial:100-s.financialScore,price:100-s.priceScore+controls.price,compliance:100-s.complianceScore,capacity:100-s.capacityScore+controls.capacity,location:100-s.locationScore+controls.location,dependency:100-s.dependencyScore+controls.dependency,sustainability:100-s.sustainabilityScore}; return Math.max(0,Math.min(100,Math.round(Object.entries(riskWeights).reduce((sum,[k,w])=>sum+factors[k as keyof typeof factors]*w,0))));}
export const level=(n:number):RiskLevel=>n<=30?'LOW':n<=60?'MEDIUM':'HIGH';
export const history=[{date:'Sep 1',score:58},{date:'Sep 7',score:64},{date:'Sep 12',score:71},{date:'Sep 17',score:78}];
